spring:
  config:
    activate:
      on-profile: dev

  cassandra:
    contact-points: localhost
    port: 9042

  data:
    redis:
      host: localhost
      port: 6379

resilience4j:
  ratelimiter:
    instances:
      shorten:
        limit-for-period: 10
        limit-refresh-period: 1m
        timeout-duration: 0s
      redirect:
        limit-for-period: 100
        limit-refresh-period: 1m
        timeout-duration: 0s

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
